## Numpy

- Python NumPy is a general-purpose array processing package which provides tools for handling the n-dimensional arrays. It provides various computing tools such as comprehensive mathematical functions, linear algebra routines. NumPy provides both the flexibility of Python and the speed of well-optimized compiled C code. It’s easy to use syntax makes it highly accessible and productive for programmers from any background.

- This NumPy tutorial helps you learn the fundamentals of NumPy from Basics to Advance, like operations on NumPy array, matrices using a huge dataset of NumPy – programs and projects.

## What is NumPy? 
- NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python. It is open-source software. It contains various features including these important ones:

- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities
- Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined using Numpy which allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

- Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.
- Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.

## Arrays in Numpy
- Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.

## Creating a Numpy Array
- Arrays in Numpy can be created by multiple ways, with various number of Ranks, defining the size of the Array. Arrays can also be created with the use of various data types such as lists, tuples, etc. The type of the resultant array is deduced from the type of the elements in the sequences.
- Note: Type of array can be explicitly defined while creating the array.

In [109]:
#creating rank1 array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [110]:
#creating rank2 array
arr = np.array([[1,2,3], [4,5,7]])
arr

array([[1, 2, 3],
       [4, 5, 7]])

In [7]:
#installation
#pip install numpy
import numpy as np
#creating array objects
arr = np.array([[1,2,3], [4,5,6]])
arr



array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# type of arr object
print('Array is type of :', type(arr))

Array is type of : <class 'numpy.ndarray'>


In [10]:
#printing array dimention
print('no. of dimention:', arr.ndim)

no. of dimention: 2


In [11]:
#printing shape of array
print('shape of arr:', arr.shape)

shape of arr: (2, 3)


In [13]:
#printing size(total no of elements) of array
print('size of array:', arr.size)

size of array: 6


In [14]:
#printing type of elements in array
print('type of elements in arr:', arr.dtype)

type of elements in arr: int32


## Array creation: There are various ways to create arrays in NumPy.

- For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.
- Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation. For example: np.zeros, np.ones, np.full, np.empty, etc.
- To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [115]:
#Numpy array from list
l1 = [1,2,3,4]
a = np.array(l1)
a

array([1, 2, 3, 4])

In [17]:
`#array creation techniques
#creating array from list with type float
arr = np.array([[1,2,3],[7,8,9]], dtype = float)
arr

array([[1., 2., 3.],
       [7., 8., 9.]])

In [112]:
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
arr1

array([[4., 7.],
       [2., 6.]])

In [22]:
#creating array from list with type int
arr = np.array([[1.2, 3.1, 3.2], [2.1, 4.1, 5.2]], dtype = int)
arr

array([[1, 3, 3],
       [2, 4, 5]])

In [113]:
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
arr2

array([[3., 6.],
       [2., 8.]])

In [116]:
#numpy array from tuple
tup = (1,2,3,4)
b = np.array(tup)
b

array([1, 2, 3, 4])

In [24]:
#creating array from tuple

b = np.array((1,2,3))
b

array([1, 2, 3])

In [26]:
#creating 3*4 array with all zeros
c = np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
#create a constant value array of complex type
d = np.full((3,3), 7, dtype = 'complex')
d

array([[7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j]])

In [29]:
d = np.full((4,3), 7, dtype = 'complex')
d

array([[7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j]])

In [32]:
#create an array with random values
e = np.random.random((2,2))#Return random floats in the half-open interval [0.0, 1.0)
e

array([[0.19253656, 0.78347515],
       [0.84214278, 0.45152065]])

In [34]:
e2 = np.random.random((3,4))
e2

array([[0.2392568 , 0.12976588, 0.53773186, 0.14613846],
       [0.01446284, 0.75527725, 0.09389902, 0.20671368],
       [0.88295148, 0.36926252, 0.39866325, 0.57728931]])

- arange: returns evenly spaced values within a given interval. step size is specified.

In [35]:
#create a sequence of integers from 0 to 30 with step of 5
#Syntax: numpy.arange([start, ]stop, [step, ]dtype=None)
f = np.arange(0,30,5)
f

array([ 0,  5, 10, 15, 20, 25])

- linspace: returns evenly spaced values within a given interval. num no. of elements are returned.

In [36]:
#crete a sequence of 10 values in range 0 to 5

g = np.linspace(0,5,10)
g

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

- **Reshaping array:** We can use reshape method to reshape an array. Consider an array with shape (a1, a2, a3, …, aN). We can reshape and convert it into another array with shape (b1, b2, b3, …, bM). The only required condition is: a1 x a2 x a3 … x aN = b1 x b2 x b3 … x bM . (i.e original size of array remains unchanged.)

In [37]:
#reshaping 3*4 array to 2*2*3 array
arr = np.array([[1,2,3,4], [7,8,9,7], [4,5,3,2]])
arr

array([[1, 2, 3, 4],
       [7, 8, 9, 7],
       [4, 5, 3, 2]])

In [38]:
arr.shape

(3, 4)

In [39]:
newarr = arr.reshape(2,2,3)
newarr

array([[[1, 2, 3],
        [4, 7, 8]],

       [[9, 7, 4],
        [5, 3, 2]]])

In [40]:
newarr.shape

(2, 2, 3)

- **Flatten array:** We can use flatten method to get a copy of array collapsed into one dimension. It accepts order argument. Default value is ‘C’ (for row-major order). Use ‘F’ for column major order.

In [41]:
#Flatten array
arr = np.array([[1,2,3], [7,8,9]])
arr

array([[1, 2, 3],
       [7, 8, 9]])

In [42]:
flarr = arr.flatten()
flarr

array([1, 2, 3, 7, 8, 9])

- **Array Indexing:** Knowing the basics of array indexing is important for analysing and manipulating the array object. NumPy offers many ways to do array indexing.

- **Slicing:** Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.
- **Integer array indexing:** In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.
- **Boolean array indexing:** This method is used when we want to pick elements from array which satisfy some condition.

In [58]:
#indexing in numpy
arr = np.array([[-2, 4,7, 0], [2,0,3,4], [3.4, -555, 9, 7], [-3, -4, 0, 5]])
arr

array([[  -2. ,    4. ,    7. ,    0. ],
       [   2. ,    0. ,    3. ,    4. ],
       [   3.4, -555. ,    9. ,    7. ],
       [  -3. ,   -4. ,    0. ,    5. ]])

In [49]:
#slicing array
temp = arr[:2, ::2]
temp

array([[-2.,  7.],
       [ 2.,  3.]])

In [52]:
arr1 = arr[::-1, ::-1]#reversing array
arr1

array([[ 5. ,  0. , -4. , -3. ],
       [ 7. ,  9. , -5. ,  3.4],
       [ 4. ,  3. ,  0. ,  2. ],
       [ 0. ,  7. ,  4. , -2. ]])

In [59]:
#integer array indexing example
temp = arr[[0,1,2,3], [0,2,1,0]]
temp

array([  -2.,    3., -555.,   -3.])

In [60]:
#boolen array indexing
cond = arr>0
temp = arr[cond]
temp

array([4. , 7. , 2. , 3. , 4. , 3.4, 9. , 7. , 5. ])

- **Basic operations:** Plethora of built-in arithmetic functions are provided in NumPy.

- **Operations on single array:** We can use overloaded arithmetic operators to do element-wise operation on array to create a new array. In case of +=, -=, *= operators, the existing array is modified.

In [62]:
#basic operation on single array

a =np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [63]:
#add 1 to every element
a1 = a+1
a1

array([2, 3, 4, 5])

In [64]:
#subtract 3 from each element
a2 = a-3
a2

array([-2, -1,  0,  1])

In [65]:
#multiply each element by 10
a3 = a*10
a3

array([10, 20, 30, 40])

In [66]:
#square each element
a4 = a**2
a4

array([ 1,  4,  9, 16], dtype=int32)

In [67]:
#modifying existing array
a*=2
a

array([2, 4, 6, 8])

In [70]:
#transpose of array
a = np.array([[1,2,3], [33,4,5], [7,8,9]])
a

array([[ 1,  2,  3],
       [33,  4,  5],
       [ 7,  8,  9]])

In [72]:
a1= a.T
a1

array([[ 1, 33,  7],
       [ 2,  4,  8],
       [ 3,  5,  9]])

- **Unary operators:** Many unary operations are provided as a method of ndarray class. This includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.

In [73]:
#unary operator in numpy
arr = np.array([[1,3,4], [4,5,7], [9,8,7]])

In [74]:
#max element of arry
arr.max()

9

In [78]:
print('row wise maximum elements:', arr.max(axis = 1))

row wise maximum elements: [4 7 9]


In [79]:
print('column wise minmum elements:', arr.min(axis=0))

column wise minmum elements: [1 3 4]


In [80]:
#sum array elements
arr.sum()

48

In [81]:
#cummulative sum along each row
arr.cumsum()

array([ 1,  4,  8, 12, 17, 24, 33, 41, 48], dtype=int32)

- **Binary operators:** These operations apply on array elementwise and a new array is created. You can use all basic arithmetic operators like +, -, /, , etc. In case of +=, -=, = operators, the existing array is modified.

In [86]:
a = np.array([[1,2], [3,4]])
b = np.array([[3,4],[2,5]])

In [87]:
#add arrays
a+b

array([[4, 6],
       [5, 9]])

In [88]:
#multiply arrays
a*b

array([[ 3,  8],
       [ 6, 20]])

In [89]:
#matrix multiplication
a.dot(b)

array([[ 7, 14],
       [17, 32]])

In [91]:
z = np.add(a,b)
z

array([[4, 6],
       [5, 9]])

In [92]:
x = np.subtract(a,b)
x

array([[-2, -2],
       [ 1, -1]])

- **Universal functions (ufunc):** NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.
- Note: All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc. 

In [93]:
#universal functions in numpy
a = np.array([0, np.pi/2, np.pi])
a

array([0.        , 1.57079633, 3.14159265])

In [94]:
print('sin values of array element', np.sin(a))

sin values of array element [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [95]:
#exponential values
a = np.array([0,1,2,3])
print('exponential of array elements:', np.exp(a))

exponential of array elements: [ 1.          2.71828183  7.3890561  20.08553692]


In [96]:
print('square root of array values', np.square(a))

square root of array values [0 1 4 9]


- **Sorting array:** There is a simple np.sort method for sorting NumPy arrays. Let’s explore it a bit.

In [97]:
a = np.array([[2,3,1], [-2, 3,-4], [7,8,9]])
a

array([[ 2,  3,  1],
       [-2,  3, -4],
       [ 7,  8,  9]])

In [99]:
#sorted array
np.sort(a, axis = None)

array([-4, -2,  1,  2,  3,  3,  7,  8,  9])

In [100]:
#sort array row wise
np.sort(a, axis = 1)

array([[ 1,  2,  3],
       [-4, -2,  3],
       [ 7,  8,  9]])

In [102]:
a

array([[ 2,  3,  1],
       [-2,  3, -4],
       [ 7,  8,  9]])

In [147]:
#specify sort algorithm
print('column wise sor by applying merge-sort:\n', np.sort(a,axis = 0, kind = 'mergesort'))

column wise sor by applying merge-sort:
 [[1 2 3]
 [4 5 6]]


In [103]:
# Example to show sorting of structured array
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
 

In [104]:
# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]


In [105]:
            
# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))
  


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]


In [106]:
           
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))

Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


## NumPy array in Python

- Python lists are a substitute for arrays, but they fail to deliver the performance required while computing large sets of numerical data. To address this issue we use a python library called NumPy. The word NumPy stands for Numerical Python. NumPy offers an array object called ndarray. They are similar to standard python sequences but differ in certain key factors.

## NumPy arrays vs inbuilt Python sequences
- Unlike lists, NumPy arrays are of fixed size, and changing the size of an array will lead to the creation of a new array while the original array will be deleted.
- All the elements in an array are of the same type.
- Numpy arrays are faster, more efficient, and require less syntax than standard python sequences.
- Note: Various scientific and mathematical Python-based packages use Numpy. They might take input as an inbuilt Python sequence but they are likely to convert the data into a NumPy array in order to attain faster processing. This explains the need to understand NumPy.

## Why is Numpy so fast?
- Numpy arrays are written mostly in C language. Being written in C, the NumPy arrays are stored in contiguous memory locations which makes them accessible and easier to manipulate. This means that you can get the performance level of a C code with the ease of writing a python program.

## Basics of NumPy Arrays

- NumPy stands for Numerical Python. It is a Python library used for working with an array. In Python, we use the list for purpose of the array but it’s slow to process. NumPy array is a powerful N-dimensional array object and its use in linear algebra, Fourier transform, and random number capabilities. It provides an array object much faster than traditional Python lists.

## Types of Array:
- One Dimensional Array
- Multi-Dimensional Array

In [118]:
#one dimensional array

lst = [1,2,3,4]
arr = np.array(lst)
arr

array([1, 2, 3, 4])

In [119]:
type(arr)

numpy.ndarray

In [121]:
#Multi-Dimensional Array:
#Data in multidimensional arrays are stored in tabular form.
#creating list

l1 = [1,2,3,4]
l2 = [7,8,9,2]
l3 = [3,4,5,7]
arr = np.array([l1,l2,l3])
arr

array([[1, 2, 3, 4],
       [7, 8, 9, 2],
       [3, 4, 5, 7]])

- Note: use [ ] operators inside numpy.array() for multi-dimensional

## Some different way of creating Numpy Array :

- numpy.fromiter(): The fromiter() function create a new one-dimensional array from an iterable object.

- Syntax: numpy.fromiter(iterable, dtype, count=-1)

In [128]:
iterable = (a*a for a in range(8))
list(iterable)

[0, 1, 4, 9, 16, 25, 36, 49]

In [125]:
arr = np.fromiter(iterable, float)
 
print("fromiter() array :",arr)

fromiter() array : [ 0.  1.  4.  9. 16. 25. 36. 49.]


In [131]:
var = 'rajukalyan'
arr = np.fromiter(var, dtype = 'U2')
arr

array(['r', 'a', 'j', 'u', 'k', 'a', 'l', 'y', 'a', 'n'], dtype='<U2')

- numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval.

- Syntax: numpy.arange([start, ]stop, [step, ]dtype=None)

In [133]:
arr = np.arange(1,20,2, dtype = np.float32)
arr

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

- numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits. 

- Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [135]:
arr = np.linspace(3.5, 10, 3)
arr

array([ 3.5 ,  6.75, 10.  ])

In [137]:
arr = np.linspace(3.5, 10, 3, dtype = np.int32)
arr

array([ 3,  6, 10])

- numpy.empty(): This function create a new array of given shape and type, without initializing value.

- Syntax: numpy.empty(shape, dtype=float, order=’C’)

In [140]:
np.empty([4,3], dtype = np.int32, order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [139]:
np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

- numpy.ones(): This function is used to get a new array of given shape and type, filled with ones(1).

- Syntax: numpy.ones(shape, dtype=None, order=’C’)

In [142]:
np.ones([4,3], dtype = np.int32, order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

- numpy.zeros(): This function is used to get a new array of given shape and type, filled with zeros(0). 

- Syntax: numpy.ones(shape, dtype=None)

In [143]:
np.zeros([4,3], dtype = np.int32, order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Python Lists VS Numpy Arrays

- NumPy is the fundamental package for scientific computing in Python. NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences. NumPy is not another programming language but a Python extension module. It provides fast and efficient operations on arrays of homogeneous data.

## Some important points about Numpy arrays:

- We can create a N-dimensional array in python using numpy.array().
- Array are by default Homogeneous, which means data inside an array must be of the same Datatype. (Note you can also create a structured array in python).
- Element wise operation is possible.
- Numpy array has the various function, methods, and variables, to ease our task of matrix computation.
- Elements of an array are stored contiguously in memory. For example, all rows of a two dimensioned array must have the same number of columns. Or a three dimensioned array must have the same number of rows and columns on each card.

In [145]:
# Single Dimensional Numpy Array;
  
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [146]:
#Multi-dimensional Numpy Array:
  
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)

[[1 2 3]
 [4 5 6]]


## Advantages of using Numpy Arrays Over Python Lists:

- consumes less memory.
- fast as compared to the python List.
- convenient to use.
## List: A list is a collection which is ordered and changeable. In Python, lists are written with square brackets.

## Some important points about Python Lists:

- The list can be homogeneous or heterogeneous.
- Element wise operation is not possible on the list.
- Python list is by default 1 dimensional. But we can create an N-Dimensional list. But then too it will be 1 D list storing another 1D list
- Elements of a list need not be contiguous in memory.
- Below are some examples which clearly demonstrate how Numpy arrays are better than Python lists by analyzing the memory consumption, execution time comparison, and operations supported by both of them.

## Example 1: Memory consumption between Numpy array and lists
- In this example, a Python list and a Numpy array of size 1000 will be created. The size of each element and then the whole size of both the containers will be calculated and comparison will be done in terms of memory consumption.

In [150]:
import numpy as np
import sys

In [151]:
#declaring list of 1000 elements
S = range(1000)

In [152]:
print('size of each element of list in bytes', sys.getsizeof(S))

size of each element of list in bytes 48


In [153]:
print('size of whole list in bytes:', sys.getsizeof(S)*len(S))

size of whole list in bytes: 48000


In [154]:
#declaring numpy array of 1000 elements
D = np.arange(1000)

In [155]:
print('size of each element of the numpy array in bytes:', D.itemsize)

size of each element of the numpy array in bytes: 4


In [156]:
print('size of the whole numpy array in bytes:', D.size*D.itemsize)

size of the whole numpy array in bytes: 4000


## Example 2: Time comparison between Numpy array and Python lists
- In this example, 2 Python lists and 2 Numpy arrays will be created and each container has 1000000 elements. Multiplication of elements in both the lists and Numpy arrays respectively will be carried out and the difference in time needed for the execution for both the containers will be analyzed to determine which one takes less time to perform the operation.

In [2]:
import numpy as np
import time
#size of array and list
size = 1000000
#declaring list
list1 = range(size)
list2 = range(size)

#declaring arrays
array1 = np.arange(size)
array2 = np.arange(size)

In [8]:
#capturing time before the multiplication of python list
initialTime = time.time()

#multiply elements of both the lists and stored in another list
resultantList = [(a*b) for a,b in zip(list1, list2)]
#calculating excution time
print('Time taken by lists to perform multiplication:', (time.time() - initialTime), 'seconds')

Time taken by lists to perform multiplication: 0.18584036827087402 seconds


In [10]:
#capturing time before the multiplication of Numpy arrays
initialTime = time.time()
#multiplying elements of both the numpy arrays and stored in another numpy array
resultantArray = array1*array2
#calculating the execution time
print('Time taken by numpy arrays to perform multiplication:', (time.time()-initialTime), 'seconds')

Time taken by numpy arrays to perform multiplication: 0.002998828887939453 seconds


## Example 3: Effect of operations on Numpy array and Python Lists
- In this example, the incapability of the Python list to carry out a basic operation is demonstrated. A Python list and a Numpy array having the same elements will be declared and an integer will be added to increment each element of the container by that integer value without looping statements. The effect of this operation on the Numpy array and Python list will be analyzed.

In [11]:
#declaring a list
ls = [1,2,3,4]
#converting list to numpy array
arr = np.array(ls)
try:
    #adding 4 to each element of list
    ls = ls+4
except(TypeError):
    print('List dont support list+int')


List dont support list+int


In [12]:
#now on array
try:
    #adding 4 to each element of numpy array
    arr = arr+4
    #printing the numpy array
    print("modified numpy array", arr)
except(TypeError):
    print('numpy arrays dont support list+int')

modified numpy array [5 6 7 8]


## How to create a vector in Python using NumPy

- Vector are built from components, which are ordinary numbers. We can think of a vector as a list of numbers, and vector algebra as operations performed on the numbers in the list. In other words vector is the numpy 1-D array.

- In order to create a vector, we use np.array method. 

- Syntax : np.array(list)
- Argument : It take 1-D list it can be 1 row and n columns or n rows and 1 column
- Return : It returns vector which is numpy.ndarray


- Note: We can create vector with other method as well which return 1-D numpy array for example np.arange(10), np.zeros((4, 1)) gives 1-D array, but most appropriate way is using np.array with the 1-D list.

In [ ]:
#creating a 1-D list(horizontal)
list1 = [1,2,3]

In [ ]:
#creating a 1-D list(vertical)

list2 = [[10],
        [11],
        [12]]

In [9]:
#creating a vector1 ...vector as row
import numpy as np
vector1 = np.array(list1)
print('Horizontal Vector')
print(vector1)

Horizontal Vector
[1 2 3]


In [7]:
#creating a vector 2 ......vector as column
vector2 = np.array(list2)
print('Vertical Vector')
print(vector2)

Vertical Vector
[[10]
 [11]
 [12]]


## Basic Arithmetic operation: 
- In this example we will see do arithmetic operations which are element-wise between two vectors of equal length to result in a new vector with the same length 

In [22]:
#creating a 1-D list (horizontal)
l1 = [1,2,3]
l2 = [8,9,10]

In [23]:
#creating a 1st vector
v1 = np.array(l1)

In [24]:
print('showing 1st vector:'  + str(v1))

showing 1st vector:[1 2 3]


In [25]:
v2 = np.array(l2)

In [26]:
print('2nd vector:' + str(v2))

2nd vector:[ 8  9 10]


In [27]:
#adding both vectors
add1 = v1+v2


In [28]:
print('vector addition:' + str(add1))

vector addition:[ 9 11 13]


In [29]:
sub = v2-v1

In [30]:
print('vector subtraction:' + str(sub))

vector subtraction:[7 7 7]


In [31]:
mul = v1*v2

In [32]:
print('vector multiplication' + str(mul))

vector multiplication[ 8 18 30]


In [33]:
div1 = v2/v1

In [34]:
print('vector division' + str(div1))

vector division[8.         4.5        3.33333333]


## Vector Dot Product 
- In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers and returns a single number. 
- For this we will use dot method.


In [35]:
# getting dot product of both the vectors
# a . b = (a1 * b1 + a2 * b2 + a3 * b3)
# a . b = (a1b1 + a2b2 + a3b3)

dot_product = v1.dot(v2)

In [36]:
print('dot product', dot_product)

dot product 56


## Vector-Scalar Multiplication 
- Multiplying a vector by a scalar is called scalar multiplication. To perform scalar multiplication, we need to multiply the scalar by each component of the vector.

In [44]:
#creating 1-D list
ls1 = [1,2,4]

In [45]:
#creating 1-D vector 
v1 = np.array(ls1)

In [46]:
print('1-D vector' + str(v1))

1-D vector[1 2 4]


In [47]:
#scalar value
scalar = 2

In [48]:
print('Scalar ' + str(scalar))

Scalar 2


In [49]:
# getting scalar multiplication value
# s * v = (s * v1, s * v2, s * v3)

scalar_mul = v1*scalar

In [50]:
print('scalar mul' + str(scalar_mul))

scalar mul[2 4 8]


## Numpy fromrecords() method

- With the help of numpy.core.fromrecords() method, we can create the record array by using the list of individual records by using numpy.core.fromrecords() method.

- Syntax : numpy.core.fromrecords([(tup1), (tup2)], metadata)

- Return : Return the record of an array.

In [53]:
# In this example we can see that using numpy.core.fromrecords() method, we are able to get to get the record array by using individual records of list.


a = np.core.records.fromrecords([(101, 'raju', 29), (301, 'kalyan', 30)], names = 'Rollno, Name, Age')

In [54]:
print(a)

[(101, 'raju', 29) (301, 'kalyan', 30)]


In [55]:
print(type(a))

<class 'numpy.recarray'>


In [56]:
print(a[0])

(101, 'raju', 29)


In [57]:
print(a.Name)

['raju' 'kalyan']


In [58]:
print(a.Age)

[29 30]


## How to Copy NumPy array into another array?

- Many times there is a need to copy one array to another. Numpy provides the facility to copy array using different methods. There are 3 methods to copy a Numpy array to another array.


- Method 1: Using np.empty_like() function

- This function returns a new array with the same shape and type as a given array.

- Syntax:

- numpy.empty_like(a, dtype = None, order = ‘K’, subok = True)

In [59]:
ary = np.array([1,2,3,4,5,7,8,9,10])

In [61]:
print('original array')
print(ary)

original array
[ 1  2  3  4  5  7  8  9 10]


In [62]:
#creating empty array similar to ary
copy = np.empty_like(ary)

In [64]:
copy[:] = ary#copy

In [65]:
print('copy of given array')
print(copy)

copy of given array
[ 1  2  3  4  5  7  8  9 10]


- Method 2: Using np.copy() function

- This function returns an array copy of the given object.

- Syntax :

- numpy.copy(a, order='K', subok=False)

In [66]:
ary = np.array([1,2,3,4,5,7,8,9,10])
print('original array')
print(ary)

original array
[ 1  2  3  4  5  7  8  9 10]


In [67]:
copy_array = np.copy(ary)

In [68]:
print('copy of given array')
print(copy_array)

copy of given array
[ 1  2  3  4  5  7  8  9 10]


In [69]:
# Method 3: Using Assignment Operator

ary = np.array([1,2,3,4,5,7,8,9,10])
print('original array')
print(ary)

original array
[ 1  2  3  4  5  7  8  9 10]


In [70]:
copy_array = ary

In [71]:
print('copy of the array', copy_array)

copy of the array [ 1  2  3  4  5  7  8  9 10]


## Appending values at the end of an NumPy array

- Let us see how to append values at the end of a NumPy array. Adding values at the end of the array is a necessary task especially when the data is not fixed and is prone to change. For this task we can use numpy.append(). This function can help us to append a single value as well as multiple values at the end of the array.

- Syntax : numpy.append(array, values, axis = None)
- Parameters :

- array : Input array.
- values : values to be added in the array.
- axis : Axis along which we want to insert the values.
- Returns : An copy of array with values being appended at the end as per the mentioned object
- along a given axis.

In [72]:
arr = np.array([1,2,3,4,7,8,5])

In [75]:
arr = np.append(arr, [777])

In [76]:
arr

array([  1,   2,   3,   4,   7,   8,   5,   7, 777])

In [77]:
arr1 = np.append(arr, [777, 888, 999])

In [78]:
arr1

array([  1,   2,   3,   4,   7,   8,   5,   7, 777, 777, 888, 999])

- Example 2 : Appending another array at the end of 1D array. You may pass a list or an array to the append function, the result will be the same.

In [79]:
arr1 = np.array([1,2,3,4])

In [80]:
arr2 = np.array([5,7,8,9])

In [81]:
arr = np.append(arr1, arr2)

In [84]:
print("after appending", arr)

after appending [1 2 3 4 5 7 8 9]


- Example 3 : Appending values at the end of the n-dimensional array. It is important that the dimensions of both the array matches otherwise it will give an error.

In [85]:
arr1 = np.arange(1, 13).reshape(2,6)

In [86]:
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [87]:
# create another array which is
# to be appended column-wise
col_arr = np.arange(5,11).reshape(1,6)

In [88]:
arr2

array([[ 5,  6,  7,  8,  9, 10]])

In [89]:
arr = np.append(arr1, col_arr, axis = 0)#column wise

In [90]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 10]])

In [99]:
# create another array which is
# to be appended row-wise
row_arr = np.array([1,2]).reshape(2,1)
row_arr

array([[1],
       [2]])

In [97]:
arr_row = np.append(arr1, row_arr, axis = 1)

In [98]:
arr_row

array([[ 1,  2,  3,  4,  5,  6,  1],
       [ 7,  8,  9, 10, 11, 12,  2]])